version: '3'

services:
  mongo:
    image: mongo:3
    container_name: mongo
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    restart: always

  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    hostname: graylog-server
    restart: always
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
      - "1514:1514/udp"
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    links:
      - mongo
      - elasticsearch
